Update ci_cd.yml

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -31,6 +31,12 @@ jobs:
     - name: Run tests
       run: |
         pytest || exit 1
+        EXIT_CODE=$?
+        echo "Pytest exit code: $EXIT_CODE"
+        if [ $EXIT_CODE -ne 0 ]; then
+          echo "Tests failed. Exiting..."
+          exit $EXIT_CODE
+        fi
         
   cd:
     needs: ci
